<?php
/**
 * @file
 * This module allows administrators to make use of Backdrop's
 * 'Access Grant' system for restricting access to nodes.
 * The module sets up a single realm and then administers the
 * appropriate settings within that realm to control the right
 * to view, edit or delete nodes.
 * Grants may be set for all nodes of the same type.
 * If a node is not assigned a grant within this realm, it will
 * remain viewable by all users unless other restrictions are
 * in place.
 *
 * All settings are held in the config file
 * simple_access_grants.settings.json
 */


/**
 * Implements hook_menu().
 */
function simple_access_grants_menu() {
  $items['admin/content/permissions'] = array(
    'title' => 'Rebuild permissions',
    'description' => 'Rebuild the Node Access permissions if access settings have been changed.',
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('simple_access_grants_admin_settings'),
    'access arguments' => array('Administer Simple Access Grants'),
    'file' => 'simple_access_grants.admin.inc',
  );
  return $items;
}


/**
 * Implements hook_permission().
 */
function simple_access_grants_permission() {
  return array(
    'administer simple access grants' => array(
      'title' => t('Administer Simple Access Grants'),
      'description' => t('Allow access to administration pages for simple access grants.'),
    ),
    'assign access to nodes' => array(
      'title' => t('Assign access to nodes'),
      'description' => t('Allow assigning of grants to nodes.'),
    ),
  );
}

/**
 * Implements hook_node_access_records().
 * Used by Backdrop when saving a node and when rebuilding permissions
 * Provides the 'locks' to prevent access to nodes
 * Locks are applied for a realm
 * They are for a node type
 * This module's locks are all for realm 'simple_access_grants'
 */
function simple_access_grants_node_access_records($node) {
  // the data structure of a lock is:
  // nid - the node ID
  // gid - the number of the role this belongs to
  // realm - predefined as 'simple_access_grant'
  // grant_view   - 0 or 1
  // grant_update - 0 or 1
  // grant_delete - 0 or 1

  // it is possible to have more than one lock per node
  // note that having a valid key to any lock will give access to the node.

  // find node type and id
  $nodetype = $node->type;
  $nid = $node->nid;


  // get grants because of node type
  $nodetypes = config_get('simple_access_grants.settings', "sag_nodetypes.$nodetype");
  if (isset($nodetypes)) {
    $nodetype_grants = isset($nodetypes['roles']) ? $nodetypes['roles'] : NULL;
  }

  //start merging
  $grants = isset($node_grants) ? $node_grants : array();
  if (isset($nodetype_grants)) {
    foreach ($nodetype_grants as $role => $gdata) {
      $grants[$role]['view'] = isset($grants[$role]['view']) ? $grants[$role]['view'] + $gdata['view'] : $gdata['view'];
      $grants[$role]['update'] = isset($grants[$role]['update']) ? $grants[$role]['update'] + $gdata['update'] : $gdata['update'];
      $grants[$role]['delete'] = isset($grants[$role]['delete']) ? $grants[$role]['delete'] + $gdata['delete'] : $gdata['delete'];
    }
  }

  // build the grant locks for each role using role number as gid
  // get role numbers from config sag_roles
  $rolenumbers = config_get('simple_access_grants.settings', 'sag_roles');
  $grantlocks = array();
  if (isset($grants) && (count($grants) > 1)) {
    foreach ($grants as $role => $gdata) {
      if (isset($gdata['view'])) {
        $grantlocks[] = array(
          'nid' => $nid,
          'gid' => $rolenumbers[$role],
          'realm' => 'simple_access_grant',
          'grant_view' => $gdata['view'] > 0 ? 1 : 0,
          'grant_update' => $gdata['update'] > 0 ? 1 : 0,
          'grant_delete' => $gdata['delete'] > 0 ? 1 : 0,
        );
      }
    }
  }
  return $grantlocks;
}


/**
 * Implements hook_node_grants().
 * This provides the keys used by Backdrop to open the 'locks' provided by
 * hook_node_access_records and stored in database table node_access
 *
 * When a user tries to perform an operation on a node, Backdrop calls
 * hook_node_grants() to determine grant ID and realm settings for the user.
 * Backdrop looks up the permitted grant ID and realm combinations for the node,
 * and compares them to the grant ID and realm keys provided here.
 * If grant ID and realm match for both
 * user and node, then the requested operation is allowed.
 *
 * $account: The user object whose grants are requested.
 * $op: The node operation to be performed, either 'view', 'update', or 'delete'.
 * Return value: An array whose keys are "realms" of grants, and whose values are
 * arrays of the grant IDs within this realm that this user is being granted.
 * Note that this module uses a single realm. Other realms may be in use
 * by other modules.
 */

function simple_access_grants_node_grants($account, $op) {
  // build the result in array 'grants'
  $grants = array();

  // anonymous users do not have grants
  if ($account->uid) {
    $user = $account->uid;

    // given the user's account, list the roles
    // for which this user has access grants, for each type of node.
    // The result will be an array of role numbers for this realm.

    // get this user's roles for the site
    $userroles = $account->roles;
    // get the role numbers registered for this module in config
    $current_roles = config_get('simple_access_grants.settings', 'sag_roles');

    if (isset($userroles)) {
      // for each of this user's roles and each node type
      // find whether there is a grant for this value of $op
      foreach ($userroles as $role => $rname) {
        // get role number from config
        $rnum = $current_roles[$rname];
        // add this role number to grants for this realm
        $grants['simple_access_grant'][] = $rnum;
      }
    }
  }
  return $grants;
}

/**
 * Implements hook_form_FORM_ID_alter().
 * Add access settings for this type of node to node_type_form.
 */
function simple_access_grants_form_node_type_form_alter(&$form, &$form_state, $form_id) {
  if ($simple_access_grants_node_type_form = simple_access_grants_node_type_form($form['#node_type'])) {
    $form = array_merge($form, $simple_access_grants_node_type_form);
  }
  $form[] = array(
    '#description' => t('Remember to rebuild permissions after changing Access Settings.')
  );
  $form['#submit'][] = 'simple_access_grants_node_type_submit';
}


/**
 * Submit callback for the node type alter form.
 */
function simple_access_grants_node_type_submit(&$form, &$form_state) {
  $type = $form_state['values']['type'];
  // save revised values in config sag_nodetypes
  // but check that some value is set
  $grants = $form_state['values']['access'];
  $found = 0;
  $grantvalue = array();
  foreach ($grants as $role => $grant) {
    if (($grant['view'] == 1) || ($grant['update'] == 1) || ($grant['delete'] == 1)) {
      config_set('simple_access_grants.settings', "sag_nodetypes.$type.roles", $grants);
      $found = 1;
    }
  }
  // if no grant is set, clear record for this node type
  if ($found == 0) {
    config_set('simple_access_grants.settings', "sag_nodetypes.$type", "");
  }
  // get rid of null entries
  $tidyup = simple_access_grants_audit();
}

/**
 * Implements hook_theme().
 */
function simple_access_grants_theme() {
  return array(
    'simple_access_grants_form' => array(
      'render element' => 'form',
      'file' => 'simple_access_grants.theme.inc',
    ),
    'simple_access_grants_page_overview_list' => array(
      'render element' => 'form',
      'file' => 'simple_access_grants.theme.inc',
    ),
  );
}


function simple_access_grants_node_type_form($nodetype) {
  // Get array of current roles excluding anonymous
  $roles = user_roles($members_only = TRUE);
  $nodetype = $nodetype->type;

  $nodetype_grants = config_get('simple_access_grants.settings', "sag_nodetypes.$nodetype.roles");

  // Set up the outer fieldset.
  $form['simple_access_grants'] = array(
    '#title' => t('Access settings'),
    '#type' => 'fieldset',
    '#description' => t('Here you can change the access settings for this content type for each role in the site.<br/>You need to rebuild permissions after saving changes here.'),
    '#collapsible' => TRUE,
    '#access' => user_access('administer nodes'),
    '#attributes' => array(
      'class' => array('simple-access-grant-settings'),
    ),
    '#weight' => 5,
    '#group' => 'additional_settings',
    '#attached' => array(
      'js' => array(backdrop_get_path('module', 'simple_access_grants') . '/simple_access_grants.js'),
    ),
  );

  $form['simple_access_grants']['access'] = array(
    '#tree' => TRUE,
    '#weight' => 5,
    '#access' => user_access('assign access to nodes') || user_access('administer nodes') || user_access('assign owner permissions'),
    '#theme' => 'simple_access_grants_form',
    '#attached' => array(
      'css' => array(backdrop_get_path('module', 'simple_access_grants') . '/simple_access_grants.css'),
    ),
  );

  // create table of roles and grants (if permission is right or user is admin)
  foreach ($roles as $role => $rolename) {
    // given the role, we need the grant for this node from $node_grants
    $node_grant = $nodetype_grants[$role];
    $form['simple_access_grants']['access'][$role] = simple_access_grants_form_row($rolename, $node_grant);
  }
  return $form;
}


/**
 * Submit callback for the node type alter form.
 */
function simple_access_grants_node_type_form_submit(&$form, &$form_state) {
  $op = isset($form_state['values']['op']) ? $form_state['values']['op'] : '';
  $type = $form_state['values']['type'];
  if ($op == t('Save content type')) {
    $grants = $form_state['values']['access'];
    config_set('simple_access_grants.settings', "sag_nodetypes.$type.roles", $grants);
  }
}


/**
 * Create a single row in the form.
 * The row has the name of the role followed by checkboxes
 * for each view, update and delete of the grant in this realm.
 * Use grant number to set checkbox defaults.
 */
function simple_access_grants_form_row($role, $grant) {
  $form['name'] = array(
    '#markup' => $role,
  );

  $form['view'] = array(
    '#type' => 'checkbox',
    '#default_value' => $grant['view'],
  );
  $form['update'] = array(
    '#type' => 'checkbox',
    '#default_value' => $grant['update'],
  );
  $form['delete'] = array(
    '#type' => 'checkbox',
    '#default_value' => $grant['delete'],
  );
  return $form;
}


/**
 * Merge two grant arrays
 */
function simple_access_grants_merge($GrantA, $GrantB) {
  // $GrantA and $GrantB are grant values
  // e.g. $grant['view'] is equal to 0 or 1
  // to be merged as one grant value
  // if either GrantA or GrantB gives a value of 1
  // then merge value is 1
  $grant['view'] = ($GrantA['view'] == 0) && ($GrantB['view'] == 0) ? 0 : 1;
  $grant['update'] = ($GrantA['update'] == 0) && ($GrantB['update'] == 0) ? 0 : 1;
  $grant['delete'] = ($GrantA['delete'] == 0) && ($GrantB['delete'] == 0) ? 0 : 1;
  return $grant;
}


/**
 * Remove null records
 */
function simple_access_grants_audit() {
  // check node type settings
  $nodetypes = config_get('simple_access_grants.settings', 'sag_nodetypes');
  $current_roles = user_roles($members_only = TRUE);
  if (isset($nodetypes)) {
    // check each node type for which there is config data
    foreach ($nodetypes as $nodetype => $ndata) {
      // rebuild config data, omitting any null grants
      // check that nodetype still exists in site
      // use backdrop function to get node type names
      $nodetypelist = node_type_get_names();
      if (isset($nodetypelist[$nodetype])) {
        // check whether data and roles exist
        $found = 0;
        if (isset($ndata['roles'])) {
          $nodegrants = array();
          foreach ($ndata as $role => $grant) {
            if (isset($grant['view']) && isset($current_roles[$role])) {
              if (($grant['view'] == 1) || ($grant['update'] == 1) || ($grant['delete'] == 1)) {
                $nodegrants[$role] = $grant;
                $found = 1;
              }
            }
          }
        }
        if ($found > 0) {
          config_set('simple_access_grants.settings', "sag_nodetypes.$nodetype", $nodegrants);
        }
      }
    }
  }

  // check role settings
  $roles = config_get('simple_access_grants.settings', 'sag_roles');
  $current_roles = user_roles($members_only = TRUE);
  $checked_roles = array();
  if (isset($roles)) {
    foreach ($roles as $role => $rnum) {
      if (isset($current_roles[$role])) {
        $checked_roles[$role] = $rnum;
      }
    }
    config_set('simple_access_grants.settings', 'sag_roles', $checked_roles);
  }
}

/**
 * Implements hook_config_info().
 */
function simple_access_grants_config_info() {
  $prefixes['simple_access_grants.settings'] = array(
    'label' => t('Simple Access Grants'),
    'group' => t('Configuration'),
  );
  return $prefixes;
}

/**
 * Implements hook_user_role_insert().
 */
function simple_access_grants_user_role_insert($role) {
  // check whether this is a new user role and if so
  // assign a role id and add the role to config.
  $role_name = $role->name;
  // is there an existing role id?
  $roles = config_get('simple_access_grants.settings', 'sag_roles');
  if (!isset($roles[$role_name])) {
    // it must be a new role so allocate an ID
    $role_max = max($roles);
    // add new role to $roles with new role id
    $roles[$role_name] = $role_max + 1;
    // update config
    config_set('simple_access_grants.settings', 'sag_roles', $roles);
  }
}

/**
 * Implements hook_user_role_delete().
 */
function simple_access_grants_user_role_delete($role) {
  // check that this role has an allocated id
  // and, if so, delete it.
  $role_name = $role->name;
  // is there an existing role id?
  $roles = config_get('simple_access_grants.settings', 'sag_roles');
  if (isset($roles[$role_name])) {
    unset($roles[$role_name]);
    // update config
    config_set('simple_access_grants.settings', 'sag_roles', $roles);
  }
  $tidyup = simple_access_grants_audit();
}
